// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using learn_english_backend.Data;

#nullable disable

namespace learn_english_backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918150014_AddLearningContent")]
    partial class AddLearningContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "lesson-1",
                            Color = "violet",
                            Description = "Bài 1 gồm các từ vựng về sức khỏe, thăm khám, điều trị, thuốc và chăm sóc răng miệng. Học và ôn tập tất cả trong cùng một bài.",
                            English = "Medical & healthcare English",
                            Icon = "book",
                            Key = "bai1",
                            Number = 1,
                            Title = "Y tế & chăm sóc sức khỏe"
                        },
                        new
                        {
                            Id = "lesson-2",
                            Color = "blue",
                            Description = "Bài 2 gồm các họ từ vựng (Noun, Verb, Adj, Adv) về quy trình khám bệnh, nha khoa, bảo hiểm y tế và bệnh viện.",
                            English = "Word Families: Health, Clinic & Hospital",
                            Icon = "medical",
                            Key = "bai2",
                            Number = 2,
                            Title = "Họ từ vựng Y tế & Sức khỏe"
                        });
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.UserWordProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MasteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("UserWordProgress", (string)null);
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.VocabularyWord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Ipa")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "Order")
                        .IsUnique();

                    b.ToTable("VocabularyWords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ipa = "/ˈkeəfl/",
                            LessonId = "lesson-1",
                            Meaning = "Cẩn thận, cẩn trọng, thận trọng",
                            Order = 1,
                            Text = "careful",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 2,
                            Ipa = "/ˈkeəfəli/",
                            LessonId = "lesson-1",
                            Meaning = "Một cách cẩn thận, chu đáo",
                            Order = 2,
                            Text = "carefully",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 3,
                            Ipa = "/prəʊˈæktɪv/",
                            LessonId = "lesson-1",
                            Meaning = "Chủ động",
                            Order = 3,
                            Text = "proactive",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 4,
                            Ipa = "/helθ/",
                            LessonId = "lesson-1",
                            Meaning = "Sức khỏe",
                            Order = 4,
                            Text = "health",
                            Type = "n."
                        },
                        new
                        {
                            Id = 5,
                            Ipa = "/helθ ˈɪʃuːz/",
                            LessonId = "lesson-1",
                            Meaning = "Các vấn đề về sức khỏe",
                            Order = 5,
                            Text = "health issues",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 6,
                            Ipa = "/dɪˈtektɪŋ/",
                            LessonId = "lesson-1",
                            Meaning = "Phát hiện, nhận biết, dò tìm",
                            Order = 6,
                            Text = "detecting",
                            Type = "v."
                        },
                        new
                        {
                            Id = 7,
                            Ipa = "/ˈsɪmptəmz/",
                            LessonId = "lesson-1",
                            Meaning = "Các triệu chứng (bệnh)",
                            Order = 7,
                            Text = "symptoms",
                            Type = "n."
                        },
                        new
                        {
                            Id = 8,
                            Ipa = "/ˈeni ˈsɪmptəmz/",
                            LessonId = "lesson-1",
                            Meaning = "Bất kỳ triệu chứng nào",
                            Order = 8,
                            Text = "any symptoms",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 9,
                            Ipa = "/ˈɜːli/",
                            LessonId = "lesson-1",
                            Meaning = "Sớm",
                            Order = 9,
                            Text = "early",
                            Type = "adv./adj."
                        },
                        new
                        {
                            Id = 10,
                            Ipa = "/triːts/",
                            LessonId = "lesson-1",
                            Meaning = "Chữa trị, điều trị, đối xử",
                            Order = 10,
                            Text = "treats",
                            Type = "v."
                        },
                        new
                        {
                            Id = 11,
                            Ipa = "/ˈtriːtɪd/",
                            LessonId = "lesson-1",
                            Meaning = "Được điều trị / Đã chữa trị",
                            Order = 11,
                            Text = "treated",
                            Type = "v."
                        },
                        new
                        {
                            Id = 12,
                            Ipa = "/ðə ˈtriːtmənt ˈprəʊses/",
                            LessonId = "lesson-1",
                            Meaning = "Quá trình / Quy trình điều trị",
                            Order = 12,
                            Text = "the treatment process",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 13,
                            Ipa = "/ðə prɪˈskraɪbd ˈtriːtmənt plæn/",
                            LessonId = "lesson-1",
                            Meaning = "Kế hoạch điều trị đã được kê đơn/chỉ định",
                            Order = 13,
                            Text = "the prescribed treatment plan",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 14,
                            Ipa = "/ˈfɜːðə(r) ˈtriːtmənt/",
                            LessonId = "lesson-1",
                            Meaning = "Việc điều trị chuyên sâu/tiếp theo",
                            Order = 14,
                            Text = "further treatment",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 15,
                            Ipa = "/ˈdʒentl/",
                            LessonId = "lesson-1",
                            Meaning = "Nhẹ nhàng, dịu dàng",
                            Order = 15,
                            Text = "gentle",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 16,
                            Ipa = "/ˈdʒentli/",
                            LessonId = "lesson-1",
                            Meaning = "Một cách nhẹ nhàng, êm ái",
                            Order = 16,
                            Text = "gently",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 17,
                            Ipa = "/ˈpeɪnkɪlə(r)z/",
                            LessonId = "lesson-1",
                            Meaning = "Thuốc giảm đau",
                            Order = 17,
                            Text = "painkiller(s)",
                            Type = "n."
                        },
                        new
                        {
                            Id = 18,
                            Ipa = "/ə prɪˈskrɪpʃn fɔː(r) ˈpeɪnkɪləz/",
                            LessonId = "lesson-1",
                            Meaning = "Đơn thuốc giảm đau",
                            Order = 18,
                            Text = "a prescription for painkillers",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 19,
                            Ipa = "/ˌæntibaɪˈɒtɪks/",
                            LessonId = "lesson-1",
                            Meaning = "Thuốc kháng sinh",
                            Order = 19,
                            Text = "antibiotics",
                            Type = "n."
                        },
                        new
                        {
                            Id = 20,
                            Ipa = "/prɪˈskraɪbd/",
                            LessonId = "lesson-1",
                            Meaning = "Được kê đơn, được chỉ định",
                            Order = 20,
                            Text = "prescribed",
                            Type = "v."
                        },
                        new
                        {
                            Id = 21,
                            Ipa = "/ə prɪˈskrɪpʃn/",
                            LessonId = "lesson-1",
                            Meaning = "Đơn thuốc, toa thuốc",
                            Order = 21,
                            Text = "a prescription",
                            Type = "n."
                        },
                        new
                        {
                            Id = 22,
                            Ipa = "/ˌəʊvə ðə ˈkaʊntə(r) ˈmedsn/",
                            LessonId = "lesson-1",
                            Meaning = "Thuốc không cần kê đơn (mua ở quầy)",
                            Order = 22,
                            Text = "over-the-counter medicine",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 23,
                            Ipa = "/maɪ ˌmedɪˈkeɪʃnz/",
                            LessonId = "lesson-1",
                            Meaning = "Thuốc men của tôi",
                            Order = 23,
                            Text = "my medications",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 24,
                            Ipa = "/sɪˈvɪə(r)/",
                            LessonId = "lesson-1",
                            Meaning = "Nghiêm trọng, nặng, dữ dội",
                            Order = 24,
                            Text = "severe",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 25,
                            Ipa = "/maɪld/",
                            LessonId = "lesson-1",
                            Meaning = "Nhẹ, êm dịu (mức độ nhẹ)",
                            Order = 25,
                            Text = "mild",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 26,
                            Ipa = "/kənˈsʌlt/",
                            LessonId = "lesson-1",
                            Meaning = "Tham khảo ý kiến, hội chẩn, tư vấn",
                            Order = 26,
                            Text = "consult",
                            Type = "v."
                        },
                        new
                        {
                            Id = 27,
                            Ipa = "/kənˈsʌlt ðə ˈdɒktə(r)/",
                            LessonId = "lesson-1",
                            Meaning = "Tham khảo ý kiến bác sĩ",
                            Order = 27,
                            Text = "consult the doctor",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 28,
                            Ipa = "/əˈpɔɪntmənt/",
                            LessonId = "lesson-1",
                            Meaning = "Cuộc hẹn, lịch hẹn (với bác sĩ/nha sĩ)",
                            Order = 28,
                            Text = "appointment",
                            Type = "n."
                        },
                        new
                        {
                            Id = 29,
                            Ipa = "/ˈʃedjuːld ən ə ˈpɔɪntmənt/",
                            LessonId = "lesson-1",
                            Meaning = "Đã lên lịch một cuộc hẹn",
                            Order = 29,
                            Text = "scheduled an appointment",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 30,
                            Ipa = "/ˈhedeɪk/",
                            LessonId = "lesson-1",
                            Meaning = "Cơn đau đầu, nhức đầu",
                            Order = 30,
                            Text = "headache",
                            Type = "n."
                        },
                        new
                        {
                            Id = 31,
                            Ipa = "/ˈdentl ˈtʃek ʌp/",
                            LessonId = "lesson-1",
                            Meaning = "Khám/kiểm tra răng miệng",
                            Order = 31,
                            Text = "dental check-up",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 32,
                            Ipa = "/ðə ˈdentɪst/",
                            LessonId = "lesson-1",
                            Meaning = "Nha sĩ, bác sĩ răng hàm mặt",
                            Order = 32,
                            Text = "the dentist",
                            Type = "n."
                        },
                        new
                        {
                            Id = 33,
                            Ipa = "/prəˈfeʃənl/",
                            LessonId = "lesson-1",
                            Meaning = "Chuyên nghiệp",
                            Order = 33,
                            Text = "professional",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 34,
                            Ipa = "/les ˈpeɪnfl/",
                            LessonId = "lesson-1",
                            Meaning = "Bớt đau đớn hơn, ít đau hơn",
                            Order = 34,
                            Text = "less painful",
                            Type = "adj. phr."
                        },
                        new
                        {
                            Id = 35,
                            Ipa = "/ɪkˈspleɪnd/",
                            LessonId = "lesson-1",
                            Meaning = "Đã giải thích, giảng giải",
                            Order = 35,
                            Text = "explained",
                            Type = "v."
                        },
                        new
                        {
                            Id = 36,
                            Ipa = "/ˈklɪəli/",
                            LessonId = "lesson-1",
                            Meaning = "Một cách rõ ràng, dễ hiểu",
                            Order = 36,
                            Text = "clearly",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 37,
                            Ipa = "/ˈθʌrəli/",
                            LessonId = "lesson-1",
                            Meaning = "Một cách kỹ lưỡng, cặn kẽ",
                            Order = 37,
                            Text = "thoroughly",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 38,
                            Ipa = "/ˈkævətiz/",
                            LessonId = "lesson-1",
                            Meaning = "Lỗ sâu răng, các vết sâu răng",
                            Order = 38,
                            Text = "cavity / cavities",
                            Type = "n."
                        },
                        new
                        {
                            Id = 39,
                            Ipa = "/fɪl ə ˈkævəti/",
                            LessonId = "lesson-1",
                            Meaning = "Trám/hàn một lỗ sâu",
                            Order = 39,
                            Text = "fill a cavity",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 40,
                            Ipa = "/ɡʌm dɪˈziːz/",
                            LessonId = "lesson-1",
                            Meaning = "Bệnh về nướu răng, viêm lợi",
                            Order = 40,
                            Text = "gum disease",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 41,
                            Ipa = "/liːd tuː/",
                            LessonId = "lesson-1",
                            Meaning = "Dẫn đến, gây ra",
                            Order = 41,
                            Text = "lead to",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 42,
                            Ipa = "/ˈsɪəriəs ˈdentl ˈprɒbləmz/",
                            LessonId = "lesson-1",
                            Meaning = "Các vấn đề nghiêm trọng về răng miệng",
                            Order = 42,
                            Text = "serious dental problems",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 43,
                            Ipa = "/ˈsɪəriəs ˈɔːrəl helθ ˈprɒbləmz/",
                            LessonId = "lesson-1",
                            Meaning = "Các vấn đề nghiêm trọng về sức khỏe răng miệng",
                            Order = 43,
                            Text = "serious oral health problems",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 44,
                            Ipa = "/ɡet ə blʌd test/",
                            LessonId = "lesson-1",
                            Meaning = "Làm xét nghiệm máu",
                            Order = 44,
                            Text = "get a blood test",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 45,
                            Ipa = "/əˈreɪndʒd tuː/",
                            LessonId = "lesson-1",
                            Meaning = "Đã sắp xếp để...",
                            Order = 45,
                            Text = "arranged to",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 46,
                            Ipa = "/tiːθ ˈwaɪtnɪŋ ˈɒpʃnz/",
                            LessonId = "lesson-1",
                            Meaning = "Các phương pháp tẩy trắng răng",
                            Order = 46,
                            Text = "teeth whitening options",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 47,
                            Ipa = "/dɪˈpendɪŋ ɒn ðə kənˈdɪʃn/",
                            LessonId = "lesson-1",
                            Meaning = "Tùy thuộc vào tình trạng",
                            Order = 47,
                            Text = "depending on the condition",
                            Type = "phr."
                        },
                        new
                        {
                            Id = 48,
                            Ipa = "/rɪˈliːv/",
                            LessonId = "lesson-1",
                            Meaning = "Làm dịu đi, giảm bớt (cơn đau/lo âu)",
                            Order = 48,
                            Text = "relieve",
                            Type = "v."
                        },
                        new
                        {
                            Id = 49,
                            Ipa = "/ˈnaɪðə(r) ˈkɒnstənt nɔː(r) ʌnˈbeərəbl/",
                            LessonId = "lesson-1",
                            Meaning = "Không liên tục cũng không quá sức chịu đựng",
                            Order = 49,
                            Text = "neither constant nor unbearable",
                            Type = "phr."
                        },
                        new
                        {
                            Id = 50,
                            Ipa = "/ɪɡˈnɔːd/",
                            LessonId = "lesson-1",
                            Meaning = "Bỏ qua, phớt lờ / Bị phớt lờ",
                            Order = 50,
                            Text = "ignored",
                            Type = "v."
                        },
                        new
                        {
                            Id = 51,
                            Ipa = "/skɪpt/",
                            LessonId = "lesson-1",
                            Meaning = "Bỏ qua, nhảy cóc, không uống (thuốc)",
                            Order = 51,
                            Text = "skipped",
                            Type = "v."
                        },
                        new
                        {
                            Id = 52,
                            Ipa = "/rɪˈsiːvd/",
                            LessonId = "lesson-1",
                            Meaning = "Đã nhận được",
                            Order = 52,
                            Text = "received",
                            Type = "v."
                        },
                        new
                        {
                            Id = 53,
                            Ipa = "/dɪˈtekt/",
                            LessonId = "lesson-2",
                            Meaning = "Phát hiện, nhận ra, tìm ra",
                            Order = 1,
                            Text = "detect",
                            Type = "v."
                        },
                        new
                        {
                            Id = 54,
                            Ipa = "/dɪˈtekʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự phát hiện, việc phát hiện",
                            Order = 2,
                            Text = "detection",
                            Type = "n."
                        },
                        new
                        {
                            Id = 55,
                            Ipa = "/dɪˈtektəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể phát hiện, có thể nhận biết",
                            Order = 3,
                            Text = "detectable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 56,
                            Ipa = "/əˈpɔɪntmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Cuộc hẹn, lịch hẹn",
                            Order = 4,
                            Text = "appointment",
                            Type = "n."
                        },
                        new
                        {
                            Id = 57,
                            Ipa = "/meɪk ən əˈpɔɪntmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Đặt lịch hẹn, hẹn gặp bác sĩ",
                            Order = 5,
                            Text = "make an appointment",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 58,
                            Ipa = "/ˈʃedjuːl ən əˈpɔɪntmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Lên lịch hẹn, đặt lịch hẹn",
                            Order = 6,
                            Text = "schedule an appointment",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 59,
                            Ipa = "/ˈdaɪəɡnəʊz/",
                            LessonId = "lesson-2",
                            Meaning = "Chẩn đoán",
                            Order = 7,
                            Text = "diagnose",
                            Type = "v."
                        },
                        new
                        {
                            Id = 60,
                            Ipa = "/ˌdaɪəɡˈnəʊsɪs/",
                            LessonId = "lesson-2",
                            Meaning = "Sự chẩn đoán, việc chẩn đoán",
                            Order = 8,
                            Text = "diagnosis",
                            Type = "n."
                        },
                        new
                        {
                            Id = 61,
                            Ipa = "/ˌdaɪəɡˈnɒstɪk/",
                            LessonId = "lesson-2",
                            Meaning = "Thuộc về chẩn đoán",
                            Order = 9,
                            Text = "diagnostic",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 62,
                            Ipa = "/əˈses/",
                            LessonId = "lesson-2",
                            Meaning = "Đánh giá, định giá",
                            Order = 10,
                            Text = "assess",
                            Type = "v."
                        },
                        new
                        {
                            Id = 63,
                            Ipa = "/əˈsesmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Sự đánh giá, cuộc đánh giá",
                            Order = 11,
                            Text = "assessment",
                            Type = "n."
                        },
                        new
                        {
                            Id = 64,
                            Ipa = "/əˈsesəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể đánh giá được",
                            Order = 12,
                            Text = "assessable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 65,
                            Ipa = "/kɔːz/",
                            LessonId = "lesson-2",
                            Meaning = "Gây ra, dẫn đến",
                            Order = 13,
                            Text = "cause",
                            Type = "v."
                        },
                        new
                        {
                            Id = 66,
                            Ipa = "/kɔːz/",
                            LessonId = "lesson-2",
                            Meaning = "Nguyên nhân, lý do",
                            Order = 14,
                            Text = "cause",
                            Type = "n."
                        },
                        new
                        {
                            Id = 67,
                            Ipa = "/triːt/",
                            LessonId = "lesson-2",
                            Meaning = "Điều trị, chữa trị",
                            Order = 15,
                            Text = "treat",
                            Type = "v."
                        },
                        new
                        {
                            Id = 68,
                            Ipa = "/ˈtriːtmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Sự điều trị, việc điều trị, liệu trình",
                            Order = 16,
                            Text = "treatment",
                            Type = "n."
                        },
                        new
                        {
                            Id = 69,
                            Ipa = "/ˈtriːtəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể điều trị được",
                            Order = 17,
                            Text = "treatable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 70,
                            Ipa = "/ˈsɜːdʒəri/",
                            LessonId = "lesson-2",
                            Meaning = "Phẫu thuật, ca phẫu thuật",
                            Order = 18,
                            Text = "surgery",
                            Type = "n."
                        },
                        new
                        {
                            Id = 71,
                            Ipa = "/ˈsɜːdʒɪkl/",
                            LessonId = "lesson-2",
                            Meaning = "Thuộc về phẫu thuật",
                            Order = 19,
                            Text = "surgical",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 72,
                            Ipa = "/ˈsɜːdʒɪkli/",
                            LessonId = "lesson-2",
                            Meaning = "Bằng phẫu thuật",
                            Order = 20,
                            Text = "surgically",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 73,
                            Ipa = "/ˈsɜːdʒən/",
                            LessonId = "lesson-2",
                            Meaning = "Bác sĩ phẫu thuật",
                            Order = 21,
                            Text = "surgeon",
                            Type = "n."
                        },
                        new
                        {
                            Id = 74,
                            Ipa = "/prɪˈskraɪb/",
                            LessonId = "lesson-2",
                            Meaning = "Kê đơn, kê thuốc",
                            Order = 22,
                            Text = "prescribe",
                            Type = "v."
                        },
                        new
                        {
                            Id = 75,
                            Ipa = "/prɪˈskrɪpʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Đơn thuốc, toa thuốc",
                            Order = 23,
                            Text = "prescription",
                            Type = "n."
                        },
                        new
                        {
                            Id = 76,
                            Ipa = "/prɪˈskraɪbd/",
                            LessonId = "lesson-2",
                            Meaning = "Được kê đơn, theo chỉ định",
                            Order = 24,
                            Text = "prescribed",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 77,
                            Ipa = "/ɪˈfekt/",
                            LessonId = "lesson-2",
                            Meaning = "Tác dụng, hiệu quả, tác động",
                            Order = 25,
                            Text = "effect",
                            Type = "n."
                        },
                        new
                        {
                            Id = 78,
                            Ipa = "/ˈsaɪd ɪfekt/",
                            LessonId = "lesson-2",
                            Meaning = "Tác dụng phụ",
                            Order = 26,
                            Text = "side effect",
                            Type = "n. phr."
                        },
                        new
                        {
                            Id = 79,
                            Ipa = "/ɪˈfektɪv/",
                            LessonId = "lesson-2",
                            Meaning = "Hiệu quả, có tác dụng",
                            Order = 27,
                            Text = "effective",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 80,
                            Ipa = "/ˌɪntərˈækt/",
                            LessonId = "lesson-2",
                            Meaning = "Tương tác, tương tác thuốc",
                            Order = 28,
                            Text = "interact",
                            Type = "v."
                        },
                        new
                        {
                            Id = 81,
                            Ipa = "/ˌɪntərˈækʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự tương tác, tương tác qua lại",
                            Order = 29,
                            Text = "interaction",
                            Type = "n."
                        },
                        new
                        {
                            Id = 82,
                            Ipa = "/ˌɪntərˈæktɪv/",
                            LessonId = "lesson-2",
                            Meaning = "Có tính tương tác",
                            Order = 30,
                            Text = "interactive",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 83,
                            Ipa = "/kənˈsʌlt/",
                            LessonId = "lesson-2",
                            Meaning = "Tham khảo ý kiến, hỏi ý kiến",
                            Order = 31,
                            Text = "consult",
                            Type = "v."
                        },
                        new
                        {
                            Id = 84,
                            Ipa = "/ˌkɒnslˈteɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Cuộc tư vấn, buổi tư vấn, sự hội chẩn",
                            Order = 32,
                            Text = "consultation",
                            Type = "n."
                        },
                        new
                        {
                            Id = 85,
                            Ipa = "/kənˈsʌltətɪv/",
                            LessonId = "lesson-2",
                            Meaning = "Mang tính tư vấn, có tính cố vấn",
                            Order = 33,
                            Text = "consultative",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 86,
                            Ipa = "/dɪˈsaɪd/",
                            LessonId = "lesson-2",
                            Meaning = "Quyết định",
                            Order = 34,
                            Text = "decide",
                            Type = "v."
                        },
                        new
                        {
                            Id = 87,
                            Ipa = "/dɪˈsɪʒn/",
                            LessonId = "lesson-2",
                            Meaning = "Quyết định, sự quyết định",
                            Order = 35,
                            Text = "decision",
                            Type = "n."
                        },
                        new
                        {
                            Id = 88,
                            Ipa = "/dɪˈsaɪsɪv/",
                            LessonId = "lesson-2",
                            Meaning = "Mang tính quyết định, dứt khoát",
                            Order = 36,
                            Text = "decisive",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 89,
                            Ipa = "/ˈdentɪst/",
                            LessonId = "lesson-2",
                            Meaning = "Nha sĩ, bác sĩ răng hàm mặt",
                            Order = 37,
                            Text = "dentist",
                            Type = "n."
                        },
                        new
                        {
                            Id = 90,
                            Ipa = "/ˈdentl/",
                            LessonId = "lesson-2",
                            Meaning = "Thuộc về răng miệng, nha khoa",
                            Order = 38,
                            Text = "dental",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 91,
                            Ipa = "/ˈreɡjələ(r)/",
                            LessonId = "lesson-2",
                            Meaning = "Thường xuyên, đều đặn",
                            Order = 39,
                            Text = "regular",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 92,
                            Ipa = "/ˌreɡjuˈlærəti/",
                            LessonId = "lesson-2",
                            Meaning = "Sự đều đặn, tính quy củ",
                            Order = 40,
                            Text = "regularity",
                            Type = "n."
                        },
                        new
                        {
                            Id = 93,
                            Ipa = "/ˈreɡjələli/",
                            LessonId = "lesson-2",
                            Meaning = "Một cách đều đặn, thường xuyên",
                            Order = 41,
                            Text = "regularly",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 94,
                            Ipa = "/əˈdʒʌst/",
                            LessonId = "lesson-2",
                            Meaning = "Điều chỉnh, căn chỉnh",
                            Order = 42,
                            Text = "adjust",
                            Type = "v."
                        },
                        new
                        {
                            Id = 95,
                            Ipa = "/əˈdʒʌstmənt/",
                            LessonId = "lesson-2",
                            Meaning = "Sự điều chỉnh, mức điều chỉnh",
                            Order = 43,
                            Text = "adjustment",
                            Type = "n."
                        },
                        new
                        {
                            Id = 96,
                            Ipa = "/əˈdʒʌstəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể điều chỉnh được",
                            Order = 44,
                            Text = "adjustable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 97,
                            Ipa = "/waɪt/",
                            LessonId = "lesson-2",
                            Meaning = "Trắng, màu trắng",
                            Order = 45,
                            Text = "white",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 98,
                            Ipa = "/ˈwaɪtn/",
                            LessonId = "lesson-2",
                            Meaning = "Làm trắng",
                            Order = 46,
                            Text = "whiten",
                            Type = "v."
                        },
                        new
                        {
                            Id = 99,
                            Ipa = "/ˈwaɪtnɪŋ/",
                            LessonId = "lesson-2",
                            Meaning = "Tẩy trắng, việc làm trắng",
                            Order = 47,
                            Text = "whitening",
                            Type = "n./adj."
                        },
                        new
                        {
                            Id = 100,
                            Ipa = "/rɪˈmuːv/",
                            LessonId = "lesson-2",
                            Meaning = "Loại bỏ, nhổ răng, lấy ra",
                            Order = 48,
                            Text = "remove",
                            Type = "v."
                        },
                        new
                        {
                            Id = 101,
                            Ipa = "/rɪˈmuːvl/",
                            LessonId = "lesson-2",
                            Meaning = "Sự loại bỏ, việc nhổ răng",
                            Order = 49,
                            Text = "removal",
                            Type = "n."
                        },
                        new
                        {
                            Id = 102,
                            Ipa = "/rɪˈmuːvəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể tháo rời, tháo lắp được",
                            Order = 50,
                            Text = "removable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 103,
                            Ipa = "/keə(r)/",
                            LessonId = "lesson-2",
                            Meaning = "Sự chăm sóc, chăm sóc",
                            Order = 51,
                            Text = "care",
                            Type = "n."
                        },
                        new
                        {
                            Id = 104,
                            Ipa = "/ˈkeəfl/",
                            LessonId = "lesson-2",
                            Meaning = "Cẩn thận, thận trọng",
                            Order = 52,
                            Text = "careful",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 105,
                            Ipa = "/ˈkeəfəli/",
                            LessonId = "lesson-2",
                            Meaning = "Một cách cẩn thận, cẩn trọng",
                            Order = 53,
                            Text = "carefully",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 106,
                            Ipa = "/ˈɪrɪteɪt/",
                            LessonId = "lesson-2",
                            Meaning = "Gây kích ứng, làm tấy rát",
                            Order = 54,
                            Text = "irritate",
                            Type = "v."
                        },
                        new
                        {
                            Id = 107,
                            Ipa = "/ˌɪrɪˈteɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự kích ứng, tình trạng tấy rát",
                            Order = 55,
                            Text = "irritation",
                            Type = "n."
                        },
                        new
                        {
                            Id = 108,
                            Ipa = "/ˈɪrɪteɪtɪŋ/",
                            LessonId = "lesson-2",
                            Meaning = "Gây khó chịu, gây kích ứng",
                            Order = 56,
                            Text = "irritating",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 109,
                            Ipa = "/ɪnˈʃʊərəns/",
                            LessonId = "lesson-2",
                            Meaning = "Bảo hiểm",
                            Order = 57,
                            Text = "insurance",
                            Type = "n."
                        },
                        new
                        {
                            Id = 110,
                            Ipa = "/ɪnˈʃʊəd/",
                            LessonId = "lesson-2",
                            Meaning = "Được bảo hiểm",
                            Order = 58,
                            Text = "insured",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 111,
                            Ipa = "/ɪnˈʃʊərəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể được bảo hiểm",
                            Order = 59,
                            Text = "insurable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 112,
                            Ipa = "/prəˈtekt/",
                            LessonId = "lesson-2",
                            Meaning = "Bảo vệ",
                            Order = 60,
                            Text = "protect",
                            Type = "v."
                        },
                        new
                        {
                            Id = 113,
                            Ipa = "/prəˈtekʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự bảo vệ",
                            Order = 61,
                            Text = "protection",
                            Type = "n."
                        },
                        new
                        {
                            Id = 114,
                            Ipa = "/prəˈtektɪv/",
                            LessonId = "lesson-2",
                            Meaning = "Mang tính bảo vệ, bảo hộ",
                            Order = 62,
                            Text = "protective",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 115,
                            Ipa = "/ˈkɒntrækt/",
                            LessonId = "lesson-2",
                            Meaning = "Hợp đồng",
                            Order = 63,
                            Text = "contract",
                            Type = "n."
                        },
                        new
                        {
                            Id = 116,
                            Ipa = "/saɪn ə ˈkɒntrækt/",
                            LessonId = "lesson-2",
                            Meaning = "Ký hợp đồng",
                            Order = 64,
                            Text = "sign a contract",
                            Type = "v. phr."
                        },
                        new
                        {
                            Id = 117,
                            Ipa = "/kənˈtræktʃuəl/",
                            LessonId = "lesson-2",
                            Meaning = "Thuộc về hợp đồng",
                            Order = 65,
                            Text = "contractual",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 118,
                            Ipa = "/prəˈsiːdʒə(r)/",
                            LessonId = "lesson-2",
                            Meaning = "Thủ tục, quy trình",
                            Order = 66,
                            Text = "procedure",
                            Type = "n."
                        },
                        new
                        {
                            Id = 119,
                            Ipa = "/prəˈsiːdʒərəl/",
                            LessonId = "lesson-2",
                            Meaning = "Thuộc về thủ tục",
                            Order = 67,
                            Text = "procedural",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 120,
                            Ipa = "/tʃuːz/",
                            LessonId = "lesson-2",
                            Meaning = "Chọn, lựa chọn",
                            Order = 68,
                            Text = "choose",
                            Type = "v."
                        },
                        new
                        {
                            Id = 121,
                            Ipa = "/tʃɔɪs/",
                            LessonId = "lesson-2",
                            Meaning = "Sự lựa chọn, lựa chọn",
                            Order = 69,
                            Text = "choice",
                            Type = "n."
                        },
                        new
                        {
                            Id = 122,
                            Ipa = "/ˈtʃəʊzn/",
                            LessonId = "lesson-2",
                            Meaning = "Đã được chọn, được tuyển chọn",
                            Order = 70,
                            Text = "chosen",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 123,
                            Ipa = "/suːt/",
                            LessonId = "lesson-2",
                            Meaning = "Phù hợp, thích hợp với",
                            Order = 71,
                            Text = "suit",
                            Type = "v."
                        },
                        new
                        {
                            Id = 124,
                            Ipa = "/ˈsuːtəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Phù hợp, thích hợp",
                            Order = 72,
                            Text = "suitable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 125,
                            Ipa = "/ˈsuːtəbli/",
                            LessonId = "lesson-2",
                            Meaning = "Một cách phù hợp, thích đáng",
                            Order = 73,
                            Text = "suitably",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 126,
                            Ipa = "/ˈæspekt/",
                            LessonId = "lesson-2",
                            Meaning = "Khía cạnh, mặt",
                            Order = 74,
                            Text = "aspect",
                            Type = "n."
                        },
                        new
                        {
                            Id = 127,
                            Ipa = "/ədˈmɪt/",
                            LessonId = "lesson-2",
                            Meaning = "Nhập viện, tiếp nhận vào viện",
                            Order = 75,
                            Text = "admit",
                            Type = "v."
                        },
                        new
                        {
                            Id = 128,
                            Ipa = "/ədˈmɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự nhập viện, sự tiếp nhận, thủ tục nhập viện",
                            Order = 76,
                            Text = "admission",
                            Type = "n."
                        },
                        new
                        {
                            Id = 129,
                            Ipa = "/ədˈmɪsəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể chấp nhận được, hợp lệ",
                            Order = 77,
                            Text = "admissible",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 130,
                            Ipa = "/ˈsætɪsfaɪ/",
                            LessonId = "lesson-2",
                            Meaning = "Làm hài lòng, thỏa mãn",
                            Order = 78,
                            Text = "satisfy",
                            Type = "v."
                        },
                        new
                        {
                            Id = 131,
                            Ipa = "/ˌsætɪsˈfækʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự hài lòng, sự thỏa mãn",
                            Order = 79,
                            Text = "satisfaction",
                            Type = "n."
                        },
                        new
                        {
                            Id = 132,
                            Ipa = "/ˌsætɪsˈfæktəri/",
                            LessonId = "lesson-2",
                            Meaning = "Vừa lòng, hài lòng, thỏa đáng",
                            Order = 80,
                            Text = "satisfactory",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 133,
                            Ipa = "/ˌsætɪsˈfæktərəli/",
                            LessonId = "lesson-2",
                            Meaning = "Một cách thỏa đáng, vừa ý",
                            Order = 81,
                            Text = "satisfactorily",
                            Type = "adv."
                        },
                        new
                        {
                            Id = 134,
                            Ipa = "/kəmˈpleɪnt/",
                            LessonId = "lesson-2",
                            Meaning = "Lời phàn nàn, đơn khiếu nại",
                            Order = 82,
                            Text = "complaint",
                            Type = "n."
                        },
                        new
                        {
                            Id = 135,
                            Ipa = "/kəmˈpleɪn/",
                            LessonId = "lesson-2",
                            Meaning = "Phàn nàn, than phiền",
                            Order = 83,
                            Text = "complain",
                            Type = "v."
                        },
                        new
                        {
                            Id = 136,
                            Ipa = "/kəmˈpleɪnɪŋ/",
                            LessonId = "lesson-2",
                            Meaning = "Hay phàn nàn, sự phàn nàn",
                            Order = 84,
                            Text = "complaining",
                            Type = "n./adj."
                        },
                        new
                        {
                            Id = 137,
                            Ipa = "/ˈdezɪɡneɪt/",
                            LessonId = "lesson-2",
                            Meaning = "Chỉ định, bổ nhiệm",
                            Order = 85,
                            Text = "designate",
                            Type = "v."
                        },
                        new
                        {
                            Id = 138,
                            Ipa = "/ˌdezɪɡˈneɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự chỉ định, sự bổ nhiệm",
                            Order = 86,
                            Text = "designation",
                            Type = "n."
                        },
                        new
                        {
                            Id = 139,
                            Ipa = "/ˈdezɪɡneɪtɪd/",
                            LessonId = "lesson-2",
                            Meaning = "Được chỉ định, dành riêng",
                            Order = 87,
                            Text = "designated",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 140,
                            Ipa = "/ˈɔːθəraɪz/",
                            LessonId = "lesson-2",
                            Meaning = "Ủy quyền, cho phép",
                            Order = 88,
                            Text = "authorize",
                            Type = "v."
                        },
                        new
                        {
                            Id = 141,
                            Ipa = "/ˌɔːθəraɪˈzeɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Sự ủy quyền, giấy ủy quyền",
                            Order = 89,
                            Text = "authorization",
                            Type = "n."
                        },
                        new
                        {
                            Id = 142,
                            Ipa = "/ˈɔːθəraɪzd/",
                            LessonId = "lesson-2",
                            Meaning = "Được ủy quyền, có thẩm quyền",
                            Order = 90,
                            Text = "authorized",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 143,
                            Ipa = "/aɪˈdentɪfaɪ/",
                            LessonId = "lesson-2",
                            Meaning = "Xác định, nhận dạng, xác minh danh tính",
                            Order = 91,
                            Text = "identify",
                            Type = "v."
                        },
                        new
                        {
                            Id = 144,
                            Ipa = "/aɪˌdentɪfɪˈkeɪʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Giấy tờ tùy thân, sự nhận dạng",
                            Order = 92,
                            Text = "identification",
                            Type = "n."
                        },
                        new
                        {
                            Id = 145,
                            Ipa = "/aɪˌdentɪˈfaɪəbl/",
                            LessonId = "lesson-2",
                            Meaning = "Có thể nhận dạng, có thể nhận biết",
                            Order = 93,
                            Text = "identifiable",
                            Type = "adj."
                        },
                        new
                        {
                            Id = 146,
                            Ipa = "/rɪˈsiːv/",
                            LessonId = "lesson-2",
                            Meaning = "Nhận, tiếp nhận",
                            Order = 94,
                            Text = "receive",
                            Type = "v."
                        },
                        new
                        {
                            Id = 147,
                            Ipa = "/rɪˈsepʃn/",
                            LessonId = "lesson-2",
                            Meaning = "Khu tiếp nhận, quầy lễ tân, sự tiếp đón",
                            Order = 95,
                            Text = "reception",
                            Type = "n."
                        },
                        new
                        {
                            Id = 148,
                            Ipa = "/rɪˈsiːvd/",
                            LessonId = "lesson-2",
                            Meaning = "Được tiếp nhận, được công nhận",
                            Order = 96,
                            Text = "received",
                            Type = "adj."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("learn_english_backend.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.UserWordProgress", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.User", "User")
                        .WithMany("WordProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("learn_english_backend.Models.Entities.VocabularyWord", "Word")
                        .WithMany("UserProgress")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.VocabularyWord", b =>
                {
                    b.HasOne("learn_english_backend.Models.Entities.Lesson", "Lesson")
                        .WithMany("Words")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.Lesson", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("WordProgress");
                });

            modelBuilder.Entity("learn_english_backend.Models.Entities.VocabularyWord", b =>
                {
                    b.Navigation("UserProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
